# Generated by Django 2.1 on 2018-09-08 20:15

from django.db import migrations, models
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='order_number')),
                ('transactio_number', models.IntegerField(verbose_name='transactio_number')),
                ('payment_datetime', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now, verbose_name='payment_datetime')),
                ('price', models.IntegerField(verbose_name='price')),
                ('status', models.CharField(max_length=128, verbose_name='status')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
