# Generated by Django 2.1 on 2018-09-04 15:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='description')),
                ('timestamp', models.DateTimeField(default=jdatetime.datetime.now, verbose_name='timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='gener')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('description', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='description')),
                ('length', models.IntegerField(verbose_name='length')),
                ('price', models.IntegerField(verbose_name='price')),
                ('actor', ckeditor.fields.RichTextField(max_length=255, verbose_name='actor')),
                ('release_date', django_jalali.db.models.jDateField(default=jdatetime.date.today, verbose_name='release_date')),
                ('timestamp', django_jalali.db.models.jDateTimeField(verbose_name='timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_movies/', verbose_name='image')),
                ('timestamp', django_jalali.db.models.jDateTimeField(verbose_name='timestamp')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_director', to='movies.People', verbose_name='director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movies.Genre', verbose_name='genres'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_producer', to='movies.People', verbose_name='producer'),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_writer', to='movies.People', verbose_name='writer'),
        ),
    ]
