# Generated by Django 2.1 on 2018-09-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='chair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.Chair', verbose_name='chair'),
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='movie'),
        ),
    ]
