# Generated by Django 2.1 on 2018-09-07 13:11

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180904_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'commet', 'verbose_name_plural': 'commets'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'people', 'verbose_name_plural': 'peoples'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'picture', 'verbose_name_plural': 'pictures'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='price',
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='chair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.Chair'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_director', to='movies.People'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_producer', to='movies.People'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_writer', to='movies.People'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
