# Generated by Django 2.1 on 2018-09-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20180907_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='chair',
        ),
    ]
